# -*- coding: utf-8 -*-
#
# Copyright (c) 2015-2016 Parisson SARL

# This file is part of Telemeta.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# TimeSide is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with TimeSide.  If not, see <http://www.gnu.org/licenses/>.

# Authors:
# Guillaume Pellerin <yomguy@parisson.com>
# Thomas Fillon <thomas@parisson.com>


data:
  image: debian:jessie
  volumes:
     - /home/parisson/CREM/Telemeta/media/:/srv/media
     - /home/parisson/CREM/Telemeta/backup/:/srv/backup
     - ./data/static:/srv/static
     - ./data/bower:/srv/bower
     - ./data/log/nginx:/var/log/nginx
     - ./data/log/uwsgi:/var/log/uwsgi
  command: "true"

db:
  image: mysql
  volumes:
    - ./scripts/:/srv/scripts
    - ./data/mysql/:/var/lib/mysql
  volumes_from:
    - data
  env_file:
    - env/prod.env

broker:
  image: redis

search:
  image: elasticsearch:1

app:
  build: .
  volumes:
    - ./app:/srv/app
    - ./telemeta:/srv/src/telemeta/telemeta
    - ./lib/TimeSide:/srv/src/timeside
  volumes_from:
    - data
  env_file:
    - env/prod.env
  command: /bin/bash scripts/app.sh
  links:
    - broker
    - db
    - search

worker:
  build: .
  volumes_from:
    - app
  env_file:
    - env/prod.env
  command: /bin/bash scripts/worker.sh
  links:
    - broker
    - db

nginx:
  image: nginx
  ports:
    - "8001:80"
  volumes:
    - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - data
  links:
    - app
    - phpmyadmin

phpmyadmin:
    image: nazarpc/phpmyadmin
    ports:
      - "1234:80"
    links:
      - db:mysql
    environment:
      - ABSOLUTE_URI=http://localhost:8000/phpmyadmin/
