# -*- coding: utf-8 -*-
#
# Copyright (c) 2015-2016 Parisson SARL

# This file is part of Telemeta.

# TimeSide is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# Telemeta is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with TimeSide.  If not, see <http://www.gnu.org/licenses/>.

# Authors:
# Guillaume Pellerin <yomguy@parisson.com>
# Thomas Fillon <thomas@parisson.com>


data:
  image: debian:jessie
  volumes:
     - /home/parisson/CREM/Telemeta/media/:/srv/media
     - ./static/:/srv/static
     - /home/parisson/CREM/Telemeta/backup/:/srv/backup
     - /srv/bower
  command: "true"

db:
  image: mysql
  volumes:
    - ./data/var/lib/mysql/:/var/lib/mysql
    - ./data/var/log/mysql/:/var/log/mysql
    - ./scripts/:/srv/scripts
  volumes_from:
    - data
  env_file:
    - app/sandbox/tm-docker-compose.env

broker:
  image: redis

search:
  image: elasticsearch:1

app:
  build: .
  volumes:
    - ./app/:/srv/app
    - ./telemeta/:/srv/src/telemeta/telemeta
  volumes_from:
    - data
  env_file:
    - app/sandbox/tm-docker-compose.env
  command: /bin/sh deploy/start_app.sh
  ports:
    - "9001:9000"
  links:
    - broker
    - db
    - search

worker:
  build: .
  volumes_from:
    - app
  env_file:
    - app/sandbox/tm-docker-compose.env
  command: /bin/sh deploy/celery_app.sh
  links:
    - broker
    - db

nginx:
  image: nginx
  ports:
    - "8001:80"
  volumes:
    - ./app/deploy/nginx-app.conf:/etc/nginx/conf.d/default.conf
    - ./var/log/nginx/:/var/log/nginx
  volumes_from:
    - data
  links:
    - app
    - phpmyadmin

phpmyadmin:
    image: nazarpc/phpmyadmin
    ports:
      - "1234:80"
    links:
      - db:mysql
    environment:
      - ABSOLUTE_URI=http://localhost:8000/phpmyadmin/
